language: python
dist: xenial
python:
  - '3.7'
install:
  - pip install pipenv
  - pipenv install --dev
before_script:
  - pipenv run black --check .
script:
  - pipenv run python -m pytest -vv --cov
after_success:
  - pipenv run bash <(curl -s https://codecov.io/bash)
